---
title: "Week7-Assignment"
format: html
---

# Assignment Week 7

## Group Members:

Angela Garcinuno Feliciano, s254630

Natali Sakurako Baba Jensen, s253573

Alena Schwerin, s251740

## Load Libraries

```{r}
library(tidyverse)
library(broom)
library(cowplot)
```

## Load Data

```{r}
biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

```{r}
biopsy
```

## Data Description

## Analysis

1.  Look at the data in PC coordinates.

```{r}
pca_fit <- biopsy %>% 
  select(where(is.numeric)) %>% # retain only numeric columns
  prcomp(scale = TRUE) # do PCA on scaled data

```

1.  then we plot the data

    ```{r}
    pca_fit %>%
      augment(biopsy) %>% # add original dataset back in
      ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + 
      geom_point(size = 1.5) +
      scale_color_manual(
        values = c(malignant = "#D55E00", benign = "#0072B2")
      ) +
      theme_half_open(12) + background_grid()
    ```

2.  Look at the rotation matrix.

#### Look at the variance explained by each PC

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues")
```

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues") |> 
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_minimal_hgrid(12)
```
